### PR TITLE
Update Translation to b95ad29

### PR DESCRIPTION
**Pull request by marocchino**
- 참고: 원문의 [diff](https://gist.github.com/marocchino/d600d3d652aa754b6152)

### CODE REVIEW

**Comment by marocchino** [comment]
```diff
diff --git a/docs/docs/02.1-jsx-in-depth.md b/docs/docs/02.1-jsx-in-depth.md
index 2557896..224b8cb 100644
--- a/docs/docs/02.1-jsx-in-depth.md
+++ b/docs/docs/02.1-jsx-in-depth.md
@@ -14,7 +14,7 @@ You don't have to use JSX with React. You can just use plain JS. However, we rec
 
 It's more familiar for casual developers such as designers.
 
-XML has the benefit of balanced open and closing tags. This helps make large trees easier to read than function calls or object literals.
+XML has the benefit of balanced opening and closing tags. This helps make large trees easier to read than function calls or object literals.
 
 It doesn't alter the semantics of JavaScript.
 
diff --git a/docs/docs/08-working-with-the-browser.md b/docs/docs/08-working-with-the-browser.md
index 2a5a3e6..dcf7458 100644
--- a/docs/docs/08-working-with-the-browser.md
+++ b/docs/docs/08-working-with-the-browser.md
@@ -18,13 +18,13 @@ Additionally, React implements a full synthetic event system such that all event
 Most of the time you should stay within React's "faked browser" world since it's more performant and easier to reason about. However, sometimes you simply need to access the underlying API, perhaps to work with a third-party library like a jQuery plugin. React provides escape hatches for you to use the underlying DOM API directly.
 
 
-## Refs and getDOMNode()
+## Refs and findDOMNode()
 
-To interact with the browser, you'll need a reference to a DOM node. Every mounted React component has a `getDOMNode()` function which you can call to get a reference to it.
+To interact with the browser, you'll need a reference to a DOM node. React has a `React.findDOMNode(component)` function which you can call to get a reference to the component's DOM node.
 
 > Note:
 >
-> `getDOMNode()` only works on mounted components (that is, components that have been placed in the DOM). If you try to call this on a component that has not been mounted yet (like calling `getDOMNode()` in `render()` on a component that has yet to be created) an exception will be thrown.
+> `findDOMNode()` only works on mounted components (that is, components that have been placed in the DOM). If you try to call this on a component that has not been mounted yet (like calling `findDOMNode()` in `render()` on a component that has yet to be created) an exception will be thrown.
 
 In order to get a reference to a React component, you can either use `this` to get the current React component, or you can use refs to refer to a component you own. They work like this:
 
@@ -32,7 +32,7 @@ In order to get a reference to a React component, you can either use `this` to g
 var MyComponent = React.createClass({
   handleClick: function() {
     // Explicitly focus the text input using the raw DOM API.
-    this.refs.myTextInput.getDOMNode().focus();
+    React.findDOMNode(this.refs.myTextInput).focus();
   },
   render: function() {
     // The ref attribute adds a reference to the component to
@@ -97,7 +97,7 @@ React provides lifecycle methods that you can specify to hook into this process.
 
 _Mounted_ composite components also support the following methods:
 
-* `getDOMNode(): DOMElement` can be invoked on any mounted component in order to obtain a reference to its rendered DOM node.
+* `findDOMNode(): DOMElement` can be invoked on any mounted component in order to obtain a reference to its rendered DOM node.
 * `forceUpdate()` can be invoked on any mounted component when you know that some deeper aspect of the component's state has changed without using `this.setState()`.
 
 
diff --git a/docs/docs/08.1-more-about-refs.md b/docs/docs/08.1-more-about-refs.md
index fc6c959..e3bbde6 100644
--- a/docs/docs/08.1-more-about-refs.md
+++ b/docs/docs/08.1-more-about-refs.md
@@ -83,7 +83,7 @@ It's as simple as:
   this.refs.myInput
   ```
 
-  You can access the component's DOM node directly by calling `this.refs.myInput.getDOMNode()`.
+  You can access the component's DOM node directly by calling `React.findDOMNode(this.refs.myInput)`.
 
 ## Completing the Example
 
@@ -99,7 +99,7 @@ It's as simple as:
       // Clear the input
       this.setState({userInput: ''}, function() {
         // This code executes after the component is re-rendered
-        this.refs.theInput.getDOMNode().focus();   // Boom! Focused!
+        React.findDOMNode(this.refs.theInput).focus();   // Boom! Focused!
       });
     },
     render: function() {
@@ -129,7 +129,7 @@ Refs are a great way to send a message to a particular child instance in a way t
 ### Benefits:
 
 - You can define any public method on your component classes (such as a reset method on a Typeahead) and call those public methods through refs (such as `this.refs.myTypeahead.reset()`).
-- Performing DOM measurements almost always requires reaching out to a "native" component such as `<input />` and accessing its underlying DOM node via `this.refs.myInput.getDOMNode()`. Refs are one of the only practical ways of doing this reliably.
+- Performing DOM measurements almost always requires reaching out to a "native" component such as `<input />` and accessing its underlying DOM node via `React.findDOMNode(this.refs.myInput)`. Refs are one of the only practical ways of doing this reliably.
 - Refs are automatically book-kept for you! If that child is destroyed, its ref is also destroyed for you. No worrying about memory here (unless you do something crazy to retain a reference yourself).
 
 ### Cautions:
diff --git a/docs/docs/10.4-test-utils.md b/docs/docs/10.4-test-utils.md
index faa1566..78d56d7 100644
--- a/docs/docs/10.4-test-utils.md
+++ b/docs/docs/10.4-test-utils.md
@@ -19,7 +19,7 @@ Simulate an event dispatch on a DOM node with optional `eventData` event data. *
 Example usage:
 
 ```javascript
-var node = this.refs.input.getDOMNode();
+var node = React.findDOMNode(this.refs.input);
 React.addons.TestUtils.Simulate.click(node);
 React.addons.TestUtils.Simulate.change(node, {target: {value: 'Hello, world'}});
 React.addons.TestUtils.Simulate.keyDown(node, {key: "Enter"});
diff --git a/docs/docs/ref-01-top-level-api.md b/docs/docs/ref-01-top-level-api.md
index 29d429d..6bea767 100644
--- a/docs/docs/ref-01-top-level-api.md
+++ b/docs/docs/ref-01-top-level-api.md
@@ -110,6 +110,14 @@ boolean isValidElement(* object)
 Verifies the object is a ReactElement.
 
 
+### React.findDOMNode
+
+```javascript
+DOMElement findDOMNode(ReactComponent component)
+```
+If this component has been mounted into the DOM, this returns the corresponding native browser DOM element. This method is useful for reading values out of the DOM, such as form field values and performing DOM measurements. When `render` returns `null` or `false`, `this.getDOMNode()` returns `null`.
+
+
 ### React.DOM
 
 `React.DOM` provides convenience wrappers around `React.createElement` for DOM components. These should only be used when not using JSX. For example, `React.DOM.div(null, 'Hello World!')`
diff --git a/docs/docs/ref-02-component-api.md b/docs/docs/ref-02-component-api.md
index 4ca1d2a..b2d3bf9 100644
--- a/docs/docs/ref-02-component-api.md
+++ b/docs/docs/ref-02-component-api.md
@@ -60,6 +60,10 @@ DOMElement getDOMNode()
 
 If this component has been mounted into the DOM, this returns the corresponding native browser DOM element. This method is useful for reading values out of the DOM, such as form field values and performing DOM measurements. When `render` returns `null` or `false`, `this.getDOMNode()` returns `null`.
 
+> Note:
+>
+> getDOMNode is deprecated and has been replaced with [React.findDOMNode()](/react/docs/top-level-api.html#react.finddomnode).
+
 
 ### isMounted
 
diff --git a/docs/docs/ref-03-component-specs.md b/docs/docs/ref-03-component-specs.md
index 0bf7526..85924f9 100644
--- a/docs/docs/ref-03-component-specs.md
+++ b/docs/docs/ref-03-component-specs.md
@@ -21,7 +21,7 @@ The `render()` method is required.
 
 When called, it should examine `this.props` and `this.state` and return a single child component. This child component can be either a virtual representation of a native DOM component (such as `<div />` or `React.DOM.div()`) or another composite component that you've defined yourself.
 
-You can also return `null` or `false` to indicate that you don't want anything rendered. Behind the scenes, React renders a `<noscript>` tag to work with our current diffing algorithm. When returning `null` or `false`, `this.getDOMNode()` will return `null`.
+You can also return `null` or `false` to indicate that you don't want anything rendered. Behind the scenes, React renders a `<noscript>` tag to work with our current diffing algorithm. When returning `null` or `false`, `React.findDOMNode(this)` will return `null`.
 
 The `render()` function should be *pure*, meaning that it does not modify component state, it returns the same result each time it's invoked, and it does not read from or write to the DOM or otherwise interact with the browser (e.g., by using `setTimeout`). If you need to interact with the browser, perform your work in `componentDidMount()` or the other lifecycle methods instead. Keeping `render()` pure makes server rendering more practical and makes components easier to think about.
 
@@ -118,14 +118,10 @@ Invoked once, both on the client and server, immediately before the initial rend
 componentDidMount()
 ```
 
-Invoked once, only on the client (not on the server), immediately after the initial rendering occurs. At this point in the lifecycle, the component has a DOM representation which you can access via `this.getDOMNode()`.
+Invoked once, only on the client (not on the server), immediately after the initial rendering occurs. At this point in the lifecycle, the component has a DOM representation which you can access via `React.findDOMNode(this)`.
 
 If you want to integrate with other JavaScript frameworks, set timers using `setTimeout` or `setInterval`, or send AJAX requests, perform those operations in this method.
 
-> Note:
->
-> Prior to v0.9, the DOM node was passed in as the last argument. If you were using this, you can still access the DOM node by calling `this.getDOMNode()`.
-
 
 ### Updating: componentWillReceiveProps
 
@@ -199,10 +195,6 @@ Invoked immediately after the component's updates are flushed to the DOM. This m
 
 Use this as an opportunity to operate on the DOM when the component has been updated.
 
-> Note:
->
-> Prior to v0.9, the DOM node was passed in as the last argument. If you were using this, you can still access the DOM node by calling `this.getDOMNode()`.
-
 
 ### Unmounting: componentWillUnmount
 
diff --git a/docs/docs/tutorial.md b/docs/docs/tutorial.md
index 1f1efad..9c1b299 100644
--- a/docs/docs/tutorial.md
+++ b/docs/docs/tutorial.md
@@ -27,7 +27,7 @@ It'll also have a few neat features:
 
 While it's not necessary to get started with this tutorial, later on we'll be adding functionality that requires `POST`ing to a running server. If this is something you are intimately familiar with and want to create your own server, please do. For the rest of you who might want to focus on learning about React without having to worry about the server-side aspects, we have written simple servers in a number of languages - JavaScript (using Node.js), Python, Ruby, Go, and PHP. These are all available on GitHub. You can [view the source](https://github.com/reactjs/react-tutorial/) or [download a zip file](https://github.com/reactjs/react-tutorial/archive/master.zip) to get started.
 
-To get started using the tutorial download, just start editing `public/index.html`.
+To get started using the tutorial, just start editing `public/index.html`.
 
 ### Getting started
 
@@ -487,14 +487,15 @@ Let's make the form interactive. When the user submits the form, we should clear
 var CommentForm = React.createClass({
   handleSubmit: function(e) {
     e.preventDefault();
-    var author = this.refs.author.getDOMNode().value.trim();
-    var text = this.refs.text.getDOMNode().value.trim();
+    var author = React.findDOMNode(this.refs.author).value.trim();
+    var text = React.findDOMNode(this.refs.text).value.trim();
     if (!text || !author) {
       return;
     }
     // TODO: send request to the server
-    this.refs.author.getDOMNode().value = '';
-    this.refs.text.getDOMNode().value = '';
+    React.findDOMNode(this.refs.author).value = '';
+    React.findDOMNode(this.refs.text).value = '';
+    return;
   },
   render: function() {
     return (
@@ -516,7 +517,7 @@ Call `preventDefault()` on the event to prevent the browser's default action of
 
 ##### Refs
 
-We use the `ref` attribute to assign a name to a child component and `this.refs` to reference the component. We can call `getDOMNode()` on a component to get the native browser DOM element.
+We use the `ref` attribute to assign a name to a child component and `this.refs` to reference the component. We can call `React.findDOMNode(component)` on a component to get the native browser DOM element.
 
 ##### Callbacks as props
 
@@ -568,14 +569,15 @@ Let's call the callback from the `CommentForm` when the user submits the form:
 var CommentForm = React.createClass({
   handleSubmit: function(e) {
     e.preventDefault();
-    var author = this.refs.author.getDOMNode().value.trim();
-    var text = this.refs.text.getDOMNode().value.trim();
+    var author = React.findDOMNode(this.refs.author).value.trim();
+    var text = React.findDOMNode(this.refs.text).value.trim();
     if (!text || !author) {
       return;
     }
     this.props.onCommentSubmit({author: author, text: text});
-    this.refs.author.getDOMNode().value = '';
-    this.refs.text.getDOMNode().value = '';
+    React.findDOMNode(this.refs.author).value = '';
+    React.findDOMNode(this.refs.text).value = '';
+    return;
   },
   render: function() {
     return (
```

**Comment by marocchino** [comment]
@reactkr/translators 리뷰 부탁드립니다.

**Comment by dittos** [comment]
LGTM :+1:

**Comment by arkist** [comment]
:+1: 머지합니다

**Pull request merged**
